instrumentation/net/http/splunkhttp/README.md
instrumentation/net/http/splunkhttp/config.go
instrumentation/net/http/splunkhttp/config_test.go
instrumentation/net/http/splunkhttp/example_test.go
instrumentation/net/http/splunkhttp/handler.go
instrumentation/net/http/splunkhttp/handler_test.go
instrumentation/net/http/splunkhttp/helpers_test.go
instrumentation/net/http/splunkhttp/server_timing_test.go

https://github.com/signalfx/splunk-otel-go/pull/18#issuecomment-808338996
>If we could add some form of this to the distro package. That would seem to make sense to me given it is supposed to be the super mega deluxe easy path for setup Splunk customers.
- Add `splunkhttp.NewHandler`
- https://github.com/signalfx/splunk-otel-go/pull/30#discussion_r606000990

Add splunkhttp.NewHandler

---

instrumentation/net/http/splunkhttp/README.md
instrumentation/net/http/splunkhttp/config.go
instrumentation/net/http/splunkhttp/config_test.go
instrumentation/net/http/splunkhttp/example_test.go
instrumentation/net/http/splunkhttp/handler.go
instrumentation/net/http/splunkhttp/handler_test.go
instrumentation/net/http/splunkhttp/server_timing.go
instrumentation/net/http/splunkhttp/server_timing_test.go

Per https://github.com/signalfx/gdi-specification/pull/32
- Rename `SPLUNK_SERVER_TIMING_CONTEXT` environmental variable to `SPLUNK_TRACE_RESPONSE_HEADER_ENABLED` together with all related variables, functions etc.

Rename ServerTiming to TraceResponseHeader

---

CHANGELOG.md
version.go

- Add [`distro`](./distro) package providing functionality to quickly setup the OpenTelemetry Go implementation with useful Splunk defaults.
- Add [`splunkhttp`](./instrumentation/net/http/splunkhttp) module providing additional Splunk specific instrumentation for `net/http`.

Prepare v0.1.0 release

---

distro/otel_test.go

- Make sure that there is no critical issue in `distro.Run` that causes it not to work at all
- Increase code coverage if someone cares 😄 
- Add a sanity test that ensures that spans are being sent to an HTTP endpoint using thrift protocol.

Add sanity test for distro.Run

---

CHANGELOG.md
version.go

The primary changes of this release is added support
for sending data directly to Splunk Observability Cloud.
- Add support for setting the [Splunk's organization access token](https://docs.splunk.com/observability/admin/authentication-tokens/org-tokens.html)
using the `SPLUNK_ACCESS_TOKEN` environmental variable or `distro.WithAccessToken` option.
It allows exporters sending data directly to the Splunk Observability Cloud.
To do so, the `OTEL_EXPORTER_JAEGER_ENDPOINT` or `distro.WithEndpoint` must be set
with Splunk back-end ingest endpoint URL: `https://ingest.<REALM>.signalfx.com/v2/trace`.
- The default Jaeger exporter URL is now loaded by
[`go.opentelemetry.io/otel/exporters/trace/jaeger`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/trace/jaeger)
module.
- Applying …

Prepare release v0.3.0

---

CHANGELOG.md
Makefile
README.md
RELEASING.md
distro/example_test.go
distro/otel.go
version.go

Have a RC-compatible release.
- Prepare release
- Update docs and examples
The primary change of this release is updating the dependency of `go.opentelemetry.io/otel*` packages from [`v0.20.0`][otel-v0.20.0] to [`v1.0.0-RC1`][otel-v1.0.0-RC1] and `go.opentelemetry.io/contrib*` packages from [`v0.20.0`][contrib-v0.20.0] to [`v0.21.0`][contrib-v0.21.0].
- Update `go.opentelemetry.io/otel*` dependencies from [`v0.20.0`][otel-v0.20.0] to [`v1.0.0-RC1`][otel-v1.0.0-RC1].
- Update `go.opentelemetry.io/contrib*` dependencies from [`v0.20.0`][contrib-v0.20.0] to [`v0.21.0`][contrib-v0.21.0].
- Drop support for Go 1.14 as [`go.opentelemetry.io@v1.0.0-RC1`](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC1) did the same.
[otel-v1.0.0-RC1]: …

Prepare release v0.4.0

---

.github/workflows/test.yml
.markdownlint.yaml
CHANGELOG.md
Makefile
README.md
RELEASING.md
instrumentation/net/http/splunkhttp/README.md

Make the docs more friendly.
- Describe the configuration better. You can preview it here: https://github.com/pellared/splunk-otel-go/tree/improve-docs
- Add markdownlint.

Improve docs

---

CHANGELOG.md
version.go

The primary change of this release is updating `go.opentelemetry.io/otel*`
dependencies to [`v1.0.0-RC2`][otel-v1.0.0-RC2] and
`go.opentelemetry.io/contrib*` dependencies to [`v0.22.0`][contrib-v0.22.0].
- Update `go.opentelemetry.io/otel*` dependencies from [`v1.0.0-RC1`][otel-v1.0.0-RC1]
to [`v1.0.0-RC2`][otel-v1.0.0-RC2].
- Update `go.opentelemetry.io/contrib*` dependencies from [`v0.21.0`][contrib-v0.21.0]
to [`v0.22.0`][contrib-v0.22.0].
[otel-v1.0.0-RC2]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC2
[otel-v1.0.0-RC1]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC1
[contrib-v0.22.0]: https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v0.22.0
[contrib-v0.21.0]: …

Release v0.5.0

---

CHANGELOG.md
pre_release.sh
version.go

The primary change of this release is updating `go.opentelemetry.io/otel*`
dependencies to [`v1.0.0-RC3`][otel-v1.0.0-RC3] and
`go.opentelemetry.io/contrib*` dependencies to [`v0.23.0`][contrib-v0.23.0].
- Update `go.opentelemetry.io/otel*` dependencies from [`v1.0.0-RC2`][otel-v1.0.0-RC2]
to [`v1.0.0-RC3`][otel-v1.0.0-RC3].
- Update `go.opentelemetry.io/contrib*` dependencies from [`v0.22.0`][contrib-v0.22.0]
to [`v0.23.0`][contrib-v0.23.0].
[otel-v1.0.0-RC3]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC3
[otel-v1.0.0-RC2]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC2
[otel-v1.0.0-RC1]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC1
[otel-v0.20.0]: …

Release v0.6.0

---

.github/workflows/ci.yml
.golangci.yml
build/go.mod
build/go.sum
build/pipeline.go
build/pipeline_test.go
build/tools.go
instrumentation/github.com/go-sql-driver/mysql/splunkmysql/test/integration_test.go
instrumentation/github.com/jackc/pgx/splunkpgx/test/integration_test.go
instrumentation/github.com/lib/pq/splunkpq/test/integration_test.go

Address https://github.com/signalfx/splunk-otel-go/issues/122
- Inline code from https://github.com/signalfx/go-pipeline to make it easier to modify/develop. I do not believe any other repo would use it anyway. The code in `piepline.go` should still be reusable.
- Add possibility to run only short tests using `-test-short` param
- Remove the `linux` build tags from integration tests
- Handle the `-v` param in the `test` task
Example usage:
```
$ ./goyek.sh test -v -test-short
===== TASK  test
Go Module: /home/rpajak/repos/splunk-otel-go/build
Cmd: go test -race -covermode=atomic -v -short -coverpkg=github.com/signalfx/splunk-otel-go/... -coverprofile=/home/rpajak/repos/splunk-otel-go/test-results/1b52cfb083dd.out ./...
=== RUN   TestRandString
=== RUN   TestRandString/0
=== RUN …
```

Filter tests in build pipeline

---

CHANGELOG.md
distro/config.go
distro/config_test.go
distro/limits.go
distro/limits_test.go
distro/otel.go

Conform with the [GDI specification](https://github.com/signalfx/gdi-specification/blob/33f1b65633c5f83acc1622bbc79f498e513a6c7c/specification/configuration.md#instrumentation-libraries):
- Distribution MUST default to 1000 for OTEL_SPAN_LINK_COUNT_LIMIT (not OpenTelemetry default)
- Distribution MUST default to 12000 for OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT (not OpenTelemetry default)
- Distribution MUST be unset "" (unlimited) for all others (not OpenTelemetry default)

Add Splunk span limit defaults

---

CHANGELOG.md
distro/config.go
distro/exporter.go

The spans were not being exported when `SPLUNK_ACCESS_TOKEN=<access_token> SPLUNK_REALM=<realm>` env vars were set.
Reference: https://docs.splunk.com/Observability/gdi/get-data-in/application/go/instrumentation/instrument-go-application.html#send-data-directly-to-observability-cloud  (this does not work)
Use the correct Splunk Observabilty Cloud OTLP over gRPC endpoint when `SPLUNK_REALM` is set.

Fix OTLP endpoint when using SPLUNK_REALM

---

example/go.mod
example/go.sum
example/main.go

The existing (before changes) example runs HTTP calls in a loop and SIGINT (CTRL+C) must be provided to stop the program. It is inconvenient during testing when it is enough to test a single call. 
Change the program to emit a single trace instead of creating a trace every 10 seconds.
After the changes, the developer can run a little script like
```sh
go run .
SPLUNK_REALM=us1 go run .
OTEL_TRACES_EXPORTER=jaeger-thrift-splunk SPLUNK_REALM=us0 go run .
OTEL_TRACES_EXPORTER=jaeger-thrift-splunk OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14268/api/traces go run .
```
go for a coffee and after a few minutes check if everything was sent to O11y Cloud as expected.
PS. The [demo example](https://github.com/signalfx/tracing-examples/tree/main/opentelemetry-tracing/opentelemetry-go/gorilla-mux …

Simplify example

---

docs/migrating.md

Leftover after https://github.com/signalfx/splunk-otel-go/pull/941
- Remove references to removed functions
- Fix hyperlink
- Fix header casing

Update migrating docs

---

.github/dependabot.yml
Makefile
build/markdownlint-cli.dockerfile
build/pipeline.go

Fixes #1179
Use dependabot for bumping markdownlint-cli to avoid manual work as well as decrease the possibility to miss an update.
- Create Dockerfile for markdownlint-cli and use it in build pipeline
- Configure dependabot to bump Dockerfiles inside `/build` directory.
See here that it works as expected: https://github.com/pellared/splunk-otel-go/pull/889

Use dependabot for bumping markdownlint-cli

---

CHANGELOG.md
distro/logger.go
distro/logger_test.go

Fixes https://github.com/signalfx/splunk-otel-go/issues/1373

OTEL_LOG_LEVEL accepts case insensitive values

---

README.md

We should refer only to the official docs 😉

Do not link to internal docs in root README.md

---

.github/workflows/ci.yml

Currently used macOS runner is deprecated:
- https://github.com/signalfx/splunk-otel-go/actions/runs/3394998999/jobs/5644295223
- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
Bump the GH runners to the current "-latest".

Bump GitHub runners

---

build/bump.go
build/clean.go
build/diff.go
build/go.mod
build/go.sum
build/golint.go
build/helpers.go
build/helpers_test.go
build/mdlint.go
build/mod.go
build/spell.go
build/test.go

There is breaking change in goyek: `TF` type renamed to `A`. Therefore the bump has to be done manually.
Reference: https://github.com/goyek/goyek/releases/tag/v2.0.0-rc.9
Bump `github.com/goyek/goyek/v2` to `v2.0.0-rc.10`.
Bump `github.com/goyek/x` to `v0.1.1`.

Bump goyek

---

.github/workflows/ci.yml

Developers likely use the latest release of Go in development and we want to catch any bugs (e.g. lint errors, race detection) with the this release before they are merged. Therefore, update the default version the CI system uses to be the latest.

Use Go 1.20 in CI

---

distro/config.go

> The SDK MUST interpret an empty value of an environment variable the same way as when the variable is unset.
Reference: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#parsing-empty-value
Handle empty env vars as it they were not set.
Currently when empty value is set then it is logging errors and fallbacks to the default value. After this change it will not longer log the error.

Handle empty env vars as it they were not set

---

CHANGELOG.md
distro/otel.go
distro/otel_test.go

The process attributes can be very useful. It is already supported by other Splunk distributions.
Add process detector OOTB.

Add process detector

---

example/README.md
example/go.mod
example/go.sum
example/main.go

1. https://github.com/gorilla/mux is archived (no longer maintained)
2. `otelhttp` has metrics instrumentation (`otelmux` does not)
Use otelhttp instead of otelmux
Manually following instructions in `example/README.md`. All metrics and spans were successfully exported.

example: use otelhttp instead of otelmux

---

example/README.md

`otlp` metrics exporter is now set by default.

Update example README.md

---

distro/otel.go

Batch span processor takes care of exporter shutdown and it makes sure it is executed once.

Simplify trace provider shutdown

---

renovate.json

Renovate should run `go mod tidy` according to
- https://docs.renovatebot.com/configuration-options/#postupdateoptions
- https://docs.renovatebot.com/modules/manager/gomod/

Renovate to run go mod tidy

---

renovate.json

See: https://docs.renovatebot.com/modules/manager/gomod/#post-update-options
I think it would be better than relying on https://github.com/signalfx/splunk-otel-go/blob/main/build/bump.go
Also it should reduce the amount of `go mod tidy` that we need to manually commit and push.

[chore] Renovate to bump indirect Go modules

---

renovate.json

We can rely on dependabot for bumping the tools under `/build`. Bumping all transitive dependencies in `/build` is too invasive and  sometimes it was breaking e.g. golangci-lint.

Update renovate.json to ignore /build

---

CHANGELOG.md
distro/exporter.go
distro/otel.go
distro/otel_test.go

Fixes https://github.com/signalfx/splunk-otel-go/issues/2688

Deprecate jaeger-thrift-splunk trace exporter

---

README.md

Blocked by:
- https://github.com/signalfx/splunk-otel-go/pull/2696
Fixes https://github.com/signalfx/splunk-otel-go/issues/2484

Update GDI spec reference to 1.6.0

---

CHANGELOG.md
distro/otel.go

Mitigate https://github.com/open-telemetry/opentelemetry-go/issues/2341 in our distribution.
1. Do not set the Scheme URL for Splunk resource attributes. They do not belong to the OTel semantic conventions anyway.
2. Remove reference to `semconv` package in `otel.go` when getting the `service.name` key (which is stable so it will not change) to reduce the possibility that we accidently use `semconv` again when creating the resource.

distro: Avoid merge resource conflict

---

.github/workflows/ci.yml

Per https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
Will unblock other PRs e.g. https://github.com/signalfx/splunk-otel-go/pull/3314

[chore] Bump macOS runners to macos-14

---

example/README.md

Fixes https://github.com/signalfx/splunk-otel-go/issues/3460
All testing was done on Windows 11.
Building the app using the Microsoft's Go fork:
```sh
rpajak@LAPTOP-K6FOL8LO MINGW64 ~/repos/splunk-otel-go (fips-win)
$ MSYS_NO_PATHCONV=1 docker run --rm -w /app -v $(pwd):/app mcr.microsoft.com/oss/go/microsoft/golang sh -c \
"cd example && GOOS=windows GOEXPERIMENT=cngcrypto go build -tags=requirefips"
go: downloading golang.org/x/sync v0.10.0
...
```
Trying to run when Windows is NOT in FIPS mode:
```sh
rpajak@LAPTOP-K6FOL8LO MINGW64 ~/repos/splunk-otel-go/example (fips-win)
$ ./example.exe
panic: cngcrypto: not in FIPS mode
goroutine 1 [running]:
crypto/internal/backend.init.0()
/usr/local/go/src/crypto/internal/backend/cng_windows.go:36 +0xb1
```
After enabling FIPS mode on Windows: …

example: FIPS mode on Windows

---

.github/workflows/ci.yml

Per https://github.com/actions/runner-images/issues/11101
ubuntu-20.04 runners are deprecated (and the actions using it can fail right now).
See: https://github.com/actions/runner-images

chore: update ubuntu runners to ubuntu-24.04
