pre_release.sh, version.go
=> Update release tooling and add version func

.github/workflows/lint.yml, .github/workflows/test.yml
=> Version actions/cache with major version only

build/build.go, build/go.mod, build/go.sum
Per https://github.com/signalfx/splunk-otel-go/pull/88#issuecomment-915496576
Bump github.com/signalfx/go-pipeline and set the `RepoPackagePrefix` config.
=> Bump github.com/signalfx/go-pipeline

CHANGELOG.md, distro/otel.go, distro/otel_test.go
As per the GDI specification: https://github.com/signalfx/gdi-specification/blob/main/specification/semantic_conventions.md#splunk-resource-attributes
=> Set splunk.distro.version attr in resource

README.md
This describes aspirational conformance, not yet reality.
=> Add GDI specification badge

CHANGELOG.md, instrumentation/github.com/jackc/pgx/splunkpgx/go.mod, instrumentation/github.com/jackc/pgx/splunkpgx/go.sum, instrumentation/github.com/jackc/pgx/splunkpgx/sql.go, instrumentation/github.com/jackc/pgx/splunkpgx/sql_test.go, instrumentation/github.com/jackc/pgx/splunkpgx/test/go.sum
=> Use jackc/pgx/v4 consistently

distro/otel.go
This was added upstream with envar support.
=> Remove TODO for BSP configuration

version.go
=> Fix splunkotel package comment

distro/README.md, distro/config.go
Little nit changes spotted during code review.
=> Refine exporter docs

RELEASING.md
Add steps that could be forgotten.
=> Update releasing process

README.md
Link new getting started and troubleshooting sections to existing documentation.
=> Add GDI spec required sections to README

build/test.go
Follows https://github.com/signalfx/splunk-otel-go/pull/1572
PS. Fix for the failures on macOS: https://github.com/signalfx/splunk-otel-go/pull/1575
=> Refactor test task

distro/otel.go
Fixes https://github.com/signalfx/splunk-otel-go/issues/1841
=> Improve distro.SDK comment

.golangci.yml, instrumentation/database/sql/splunksql/test/suite_test.go
Fixes https://github.com/signalfx/splunk-otel-go/issues/1967
=> Enable rowserrcheck

RELEASING.md
Leftover after https://github.com/signalfx/tracing-examples/pull/144
=> Update hyperlink to example

example/otel-config.yaml
This reverts commit 8cef1ed33297c9e8f348346b6b0b2da0225ab89e.
I made a mistake as I should remove it from other repo. I already fixed it there: https://github.com/signalfx/tracing-examples/pull/152
=> Revert "Delete unsed otel-config.yaml (#1959)"

CHANGELOG.md, instrumentation/database/sql/splunksql/config.go, instrumentation/database/sql/splunksql/test/db_metrics_test.go
Fixes https://github.com/signalfx/splunk-otel-go/issues/1976
=> splunksql: Add WithMeterProvider

distro/otel_test.go
Fixes https://github.com/signalfx/splunk-otel-go/issues/2260
=> distro: Set none exporters in TestMain

distro/otel_test.go
Fixes https://github.com/signalfx/splunk-otel-go/issues/2261
=> distro: Refactor assertions

CONTRIBUTING.md
From https://github.com/signalfx/gdi-specification/blob/main/specification/templates/CONTRIBUTING.md#contributor-license-agreement
=> docs: Require CLA

example/docker-compose.yaml
Tested locally (data was send to Splunk o11y Cloud)
=> Bump opentelemetry-collector-contrib to 0.80.0

distro/otel.go, distro/otel_test.go
Towards https://github.com/signalfx/splunk-otel-go/issues/2484
Per https://github.com/signalfx/gdi-specification/pull/252
=> Update log message when service name is not set

example/README.md, example/docker-compose-splunk.yaml
Make it easier to test our distribution with https://github.com/signalfx/splunk-otel-collector
=> Facilitate e2e testing with splunk-otel-collector

renovate.json
Inspired by https://github.com/open-telemetry/opentelemetry-go/pull/5772
Use https://docs.renovatebot.com/configuration-options/#groupname
=> Group renovate PRs

CONTRIBUTING.md
Per:
- https://github.com/signalfx/gdi-specification/pull/346
- https://github.com/signalfx/gdi-specification/pull/347
=> chore: update contributing to documentation

distro/exporter.go, distro/otel_test.go
- Fix Lower Case `log` in newOTLPLogExporter
- Fix Triple `s` in assertHasSpan
=> Fix minor letter errors
